# DO NOT CHANGE BELOW THIS LINE

# temporarily removed "cd onedknap && $(MAKE) $@ && cd ..&&\" due to linker issue

all dep clean indent tests::	
	cd coordesc && $(MAKE) $@ && cd .. \\
	cd projcoordesc && $(MAKE) $@ && cd .. \\
	cd varcoordesc && $(MAKE) $@ && cd .. \\
	cd gfsdesc && $(MAKE) $@ && cd .. \\
	cd hookejeeves && $(MAKE) $@ && cd .. \\
	cd lins  && $(MAKE) $@ && cd .. 

