# DO NOT CHANGE BELOW THIS LINE

# temporarily removed "cd onedknap && $(MAKE) $@ && cd ..&&\" due to linker issue

all dep clean indent tests::	
	cd dichotls && $(MAKE) $@ && cd .. \\
	cd quadls && $(MAKE) $@ && cd ..
	

